// Generated by gencpp from file osr_msgs/Tracks.msg
// DO NOT EDIT!


#ifndef OSR_MSGS_MESSAGE_TRACKS_H
#define OSR_MSGS_MESSAGE_TRACKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/Odometry.h>
#include <osr_msgs/Track.h>

namespace osr_msgs
{
template <class ContainerAllocator>
struct Tracks_
{
  typedef Tracks_<ContainerAllocator> Type;

  Tracks_()
    : header()
    , odom()
    , tracks()  {
    }
  Tracks_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , odom(_alloc)
    , tracks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _odom_type;
  _odom_type odom;

   typedef std::vector< ::osr_msgs::Track_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::osr_msgs::Track_<ContainerAllocator> >::other >  _tracks_type;
  _tracks_type tracks;





  typedef boost::shared_ptr< ::osr_msgs::Tracks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osr_msgs::Tracks_<ContainerAllocator> const> ConstPtr;

}; // struct Tracks_

typedef ::osr_msgs::Tracks_<std::allocator<void> > Tracks;

typedef boost::shared_ptr< ::osr_msgs::Tracks > TracksPtr;
typedef boost::shared_ptr< ::osr_msgs::Tracks const> TracksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osr_msgs::Tracks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osr_msgs::Tracks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace osr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'osr_msgs': ['/home/kyle/USR_SNU_MODULE/SNU_Integrated_v2/src/osr/osr_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::osr_msgs::Tracks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osr_msgs::Tracks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osr_msgs::Tracks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osr_msgs::Tracks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osr_msgs::Tracks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osr_msgs::Tracks_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osr_msgs::Tracks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e904ed11bcc18b45d7cfb15a9dbaeb75";
  }

  static const char* value(const ::osr_msgs::Tracks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe904ed11bcc18b45ULL;
  static const uint64_t static_value2 = 0xd7cfb15a9dbaeb75ULL;
};

template<class ContainerAllocator>
struct DataType< ::osr_msgs::Tracks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osr_msgs/Tracks";
  }

  static const char* value(const ::osr_msgs::Tracks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osr_msgs::Tracks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "####################\n\
# osr_msgs tracks message\n\
####################\n\
# Header\n\
Header header\n\
\n\
# Robot Pose\n\
nav_msgs/Odometry odom\n\
\n\
# Track \n\
Track[] tracks\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nav_msgs/Odometry\n\
# This represents an estimate of a position and velocity in free space.  \n\
# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n\
# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n\
Header header\n\
string child_frame_id\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertainty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: osr_msgs/Track\n\
####################\n\
# osr_msgs track message\n\
####################\n\
# ID\n\
uint8 id\n\
\n\
# Type (1: PERSON, 2: CAR)\n\
uint8 type\n\
\n\
# Posture (1: STAND, 2: SIT DOWN, 3: LIE DOWN)\n\
uint8 posture\n\
\n\
# Activity score\n\
# float32 activity\n\
\n\
# Bounding box\n\
osr_msgs/BoundingBox bbox_pose\n\
osr_msgs/BoundingBox bbox_velocity\n\
\n\
# State\n\
geometry_msgs/Pose pose\n\
geometry_msgs/Twist twist\n\
\n\
# 3D Bounding Box\n\
\n\
\n\
================================================================================\n\
MSG: osr_msgs/BoundingBox\n\
####################\n\
# osr_msgs bounding box message\n\
####################\n\
\n\
uint32 x\n\
uint32 y \n\
uint32 height\n\
uint32 width\n\
";
  }

  static const char* value(const ::osr_msgs::Tracks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osr_msgs::Tracks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.odom);
      stream.next(m.tracks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tracks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osr_msgs::Tracks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osr_msgs::Tracks_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "odom: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.odom);
    s << indent << "tracks[]" << std::endl;
    for (size_t i = 0; i < v.tracks.size(); ++i)
    {
      s << indent << "  tracks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::osr_msgs::Track_<ContainerAllocator> >::stream(s, indent + "    ", v.tracks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSR_MSGS_MESSAGE_TRACKS_H
